name       : qt6-declarative
version    : 6.5.1
release    : 4
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qtdeclarative-everywhere-src-6.5.1.tar.xz : 201148f9614a65d169a85cd0d0fbd414603498da6ff330c4e0835ecd962dce79
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Classes for QML and JavaScript languages
description: |
    The Qt Quick module is the standard library for writing QML applications. While the Qt QML module provides the QML engine and language infrastructure, the Qt Quick module provides all the basic types necessary for creating user interfaces with QML.
builddeps  :
    - pkgconfig(Qt6ShaderTools)
    - qt6-languageserver-devel
setup      : |
    %cmake_ninja -DINSTALL_PUBLICBINDIR=usr/bin -DQT_BUILD_EXAMPLES=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    cd $installdir
    install -dm00755 usr/bin
    while read _line; do
        ln -s $_line
    done < %workdir%/solusBuildDir/user_facing_tool_links.txt
    ln -s /usr/lib64/qt6/qmlcachegen $installdir/usr/bin/qmlcachegen6
patterns   :
    - devel :
        - /usr/bin/qml*
        - /usr/lib64/qt6/bin/qml*
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
# TODO: Do something about .prl files
