name       : qt6-declarative
version    : 6.3.0
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtdeclarative-everywhere-src-6.3.0.tar.xz : d294b029dc2b2d4f65da516fdc3b8088d32643eb7ff77db135a8b9ce904caa37
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Classes for QML and JavaScript languages
description: |
    The Qt Quick module is the standard library for writing QML applications. While the Qt QML module provides the QML engine and language infrastructure, the Qt Quick module provides all the basic types necessary for creating user interfaces with QML.
builddeps  :
    - pkgconfig(Qt6ShaderTools)
    - qt6-languageserver-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-find-languageserverprivate.patch
    %cmake_ninja -DINSTALL_PUBLICBINDIR=usr/bin -DQT_BUILD_EXAMPLES=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    cd $installdir
    install -dm00755 usr/bin
    while read _line; do
        ln -s $_line
    done < %workdir%/solusBuildDir/user_facing_tool_links.txt
    ln -s /usr/lib64/qt6/qmlcachegen $installdir/usr/bin/qmlcachegen6
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
