name       : qt6-declarative
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtdeclarative-everywhere-src-6.2.1.tar.xz : 5aeb841a5665f79672a302569754ea7d541c69102c551707e43489e797213c71
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Classes for QML and JavaScript languages
description: |
    The Qt Quick module is the standard library for writing QML applications. While the Qt QML module provides the QML engine and language infrastructure, the Qt Quick module provides all the basic types necessary for creating user interfaces with QML.
builddeps  :
    - pkgconfig(Qt6ShaderTools)
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-warning-about-shadertools.patch
    %cmake_ninja -DINSTALL_PUBLICBINDIR=usr/bin -DQT_BUILD_EXAMPLES=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    cd $installdir
    install -dm00755 usr/bin
    while read _line; do
        ln -s $_line
    done < %workdir%/solusBuildDir/user_facing_tool_links.txt
    ln -s /usr/lib64/qt6/qmlcachegen $installdir/usr/bin/qmlcachegen6
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
